spring:
  mvc:
    hiddenmethod.filter.enabled: true
  profiles:
    active: local-db
    
---

spring:
  config.activate.on-profile: local-db
  
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass
    driver-class-name: org.postgresql.Driver
  h2.console:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: joo26sk@gmail.com
    password: 
    properties:
      mail.smtp:
        auth: true
        timeout: 5000
        starttls.enable: true
app:
  host: http://localhost:8080
server:
  tomcat:
    max-http-form-post-size: 5MB

logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace      
    
    
---

spring:
  config.activate.on-profile: local
  
  datasource:
    url: jdbc:h2:file:./testdb;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
app:
  host: http://localhost:8080
    
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace      
    
---

spring:
  config.activate.on-profile: test
      
  datasource:
    url: jdbc:h2:mem:testdb
